version: "3"

services:
  app:
    build: .
    volumes:
      - ./migrations:/app/migrations
    command: bash -c "alembic upgrade head && python src/main.py"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
